version: '3.3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  dbhost:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "21003:5432"

  server:
    build: ./src/server
    hostname: server
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - '8000:8000'
    command: >
      sh -c "sleep 15 && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./src/server/.env
    volumes:
      - ./src/server:/server
    links:
      - dbhost
      - redis
    depends_on:
      - dbhost
      - redis

  client:
    build: ./src/client
    hostname: client
    restart: unless-stopped
    stdin_open: true
    tty: true
    working_dir: /client
    ports:
      - '3000:3000'
    links:
      - server
    volumes:
      - ./src/client:/client
    env_file:
      - ./src/client/.env
    command: >
      sh -c "npm install -g npm@latest && npm install && npm run dev"
    depends_on:
      - server

  web:
    hostname: web
    restart: unless-stopped
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./src/web/Dockerfile
    ports:
      - '6443:443'
      - '6080:80'
    depends_on:
      - server
      - client